Allow octets type to accept string and integer values for parsing
pyradius/pyrad pull request #155
Opened 2021-05-23 09:44 UTC by nward

The juniper/ERX dictionary from the FreeRADIUS project includes using octets attributes with values, which are written in the dictionary as integers, i.e.:
```
ATTRIBUTE	ERX-Acct-Request-Reason			210	octets
VALUE	ERX-Acct-Request-Reason		Acct-Start-Ack		1
VALUE	ERX-Acct-Request-Reason		Periodic		2
VALUE	ERX-Acct-Request-Reason		IP-Active		4
...etc...
```

pyrad doesn't parse this at present, and errors out as `"1"` in python is not of bytes type.

This PR adds this functionality, by allowing either str or bytes starting with `0x`, and checking for digits-only values, and packing them as an integer to get a bytes output the same as if the `0x` integer value had been passed.

Additionally, in the `EncodeOctets` function (and many Encode* function in tools.py) the parameter is called `str`, which conflicts with the python basic string type. In the EncodeOctets function I have renamed this to `octetstring`.

2021-05-23 10:17 UTC, nward commented
I've subsequently added a fix for #152, and tests for it. Thanks!

2021-07-14 13:17 UTC, nerosketch requested changes

2021-07-14 13:17 UTC, nerosketch commented on pyrad/tools.py
>      if type(octetstring) == bytes and octetstring.startswith(b'0x'):
Python has 'isinstance' for it. Like this:
isinstance(octetstring, bytes)

2021-07-14 13:17 UTC, nerosketch commented on pyrad/tools.py
> -        return binascii.unhexlify(hexstring)
isinstance(octetstring, str)

2021-07-14 13:17 UTC, nerosketch commented on pyrad/tools.py
>      elif type(octetstring) == str and octetstring.isdecimal():
isinstance(octetstring, str)

2021-07-14 13:31 UTC, nerosketch requested changes

2021-07-14 13:31 UTC, nerosketch commented on pyrad/tools.py
> +    if type(octetstring) == bytes and octetstring.startswith(b'0x'):
Python has 'isinstance' for it. Like this:
`if isinstance(octetstring, bytes) and octetstring.startswith(b'0x'):`

2021-07-14 13:31 UTC, nerosketch commented on pyrad/tools.py
> +    elif type(octetstring) == str and octetstring.startswith('0x'):
`isinstance(octetstring, str)`

2021-07-14 13:31 UTC, nerosketch commented on pyrad/tools.py
> +    elif type(octetstring) == str and octetstring.isdecimal():
`isinstance(octetstring, str)`

2021-07-14 13:35 UTC, nerosketch commented
I need these changes too. I also have "juniper", and I have similar error.

2021-07-14 13:50 UTC, nward commented
Thanks @nerosketch - I have no idea why I used type() rather than isinstance.. brain fart perhaps!

2021-07-14 18:20 UTC, Istvan91 commented
looks good to me - I'll try to push a new version this weekend.

2021-07-14 18:21 UTC, merged